### ISSUE TITLE
Releasing RGB data

### ISSUE THREAD

**Issue by Guptajakala** [bayesian-object-tracking/object_tracking_dataset#1]
I will possibly be using this dataset as a benchmark if the RGB data is provided as well. Are you still planning to release the RGB data?

**Comment by wumanu** [comment]
> I will possibly be using this dataset as a benchmark if the RGB data is provided as well. Are you still planning to release the RGB data?

Unfortunately this project is not ongoing anymore and the dataset will stay as is, we will not be able to provide any extensions. I will update the description accordingly.
